Name: Develop
Protocol:
  Secure: https
  Normal: http
Domain: fbpostmonitor.aa-dev.com
DBInfo:
  main:
    w: mysql://root:18071990@localhost/db_fbpostmon
    r: mysql://root:18071990@localhost/db_fbpostmon
DB:
  SQLLib: ${AAFW_DIR}/plugins/db_sql
CacheDir: ${AAFW_DIR}/cache

Facebook:
  Admin:
    Permissions:
      1: publish_actions
      2: manage_pages

MemcacheInfo:
  port: 11211
  server: localhost

Log4php:
  configFileName: logger_config.php
  loggers:
    batch-request:
      level: DEBUG
  appenders:
    db:
      dsn: mysql:host=localhost;dbname=db_fbpostmon
      user: root
      password: 18071990
      table: log4php_log
    file:
      name: /tmp/batch_request-%s.log
Mail:
  Default:
    FromAddress: noreply@aainc.co.jp
    BccAddress: 
    Envelope: noreply@aainc.co.jp
    Charset: ISO-2022-JP
    RealCharset: ISO-2022-JP-MS
      
